---
sidebar: sidebar 
permalink: rn/about.html 
keywords: about, about this release, current release 
summary: 'La documentazione di questo sito descrive l"API DI Astra Control REST e le relative tecnologie di automazione disponibili con Astra Control.' 
---
= A proposito di questa release
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La documentazione disponibile in questo sito descrive l'API REST di Astra Control e le relative tecnologie di automazione disponibili con la release di agosto 2022 (22.08) di Astra Control. In particolare, questa release dell'API REST è inclusa con le corrispondenti release 22.08 di Astra Control Center e Astra Control Service.

Per ulteriori informazioni su questa release e sulle release precedenti, consultare le pagine e i siti seguenti:

* link:../rn/whats_new.html["Novità dell'API REST di Astra Control"]
* link:../endpoints/resources.html["Risorse REST ed endpoint"]
* https://docs.netapp.com/us-en/astra-control-center-2208/["Documentazione di Astra Control Center 22.08"^]
* https://docs.netapp.com/us-en/astra-control-service/["Documentazione del servizio Astra Control"^]
* link:../aa-earlier-versions.html["Versioni precedenti della documentazione di Astra Automation"]


Seguici su Twitter @NetAppDoc. Invia un feedback sulla documentazione diventando un link:https://docs.netapp.com/us-en/contribute/["Collaboratore di GitHub"^] oppure inviare un'e-mail all'indirizzo doccomments@netapp.com.
